flightgoggles_uav_dynamics:
  init_pose: [0.3, 52.0, 2.5, 0.0, 0.0, -0.707, 0.707]
challenge_name: "Challenge Easy"
timeout: 200.0
gate_names: ['Gate2']
gate_width: 0.3
results_location: "/home/medusa/catkin_ws/results.yaml"
