Gate1:
  nominal_location: [[-0.009051204, -34.8755, 3.071861], [-0.008949876, -32.9505, 3.071861], [-0.008949876, -32.9505, 1.134362], [-0.009051204, -34.8755, 1.134362]]
  perturbation_bound: [2.5, 2.5, 5.0]
Gate13:
  nominal_location: [[1.237332, 9.001728, 2.9625], [3.162332, 9.001728, 2.9625], [3.162332, 9.001728, 1.025], [1.237332, 9.001728, 1.025]]
  perturbation_bound: [2.5, 2.5, 5.0]
Gate3:
  nominal_location: [[-0.3703381, -12.99827, 4.728], [-0.3699976, -11.45827, 4.728], [-0.3699976, -11.45827, 3.177999], [-0.3703381, -12.99827, 3.177999]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate4:
  nominal_location: [[-31.56487, -13.929, 6.99714], [-30.04735, -13.929, 7.259325], [-29.78347, -13.929, 5.731955], [-31.30098, -13.929, 5.469769]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate5:
  nominal_location: [[-20.94317, 14.607, 2.515013], [-20.94283, 16.147, 2.515013], [-20.94283, 16.147, 0.965013], [-20.94317, 14.607, 0.965013]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate7:
  nominal_location: [[16.2506, 41.63, 11.32092], [17.79061, 41.63, 11.32092], [17.79061, 41.63, 9.770914], [16.2506, 41.63, 9.770914]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate8:
  nominal_location: [[-3.430186, 11.79953, 6.122593], [-3.430186, 12.97997, 6.122593], [-3.430186, 11.79952, 4.911986], [-3.430186, 12.97997, 4.911986]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate9:
  nominal_location: [[-6.40867, -12.13678, 4.152941], [-8.208672, -12.13678, 4.152941], [-6.408669, -12.13678, 2.306941], [-8.208672, -12.13678, 2.306941]]
  perturbation_bound: [0.0, 0.0, 2.0]
Gate10:
  nominal_location: [[18.15111, 3.631447, 7.229498], [16.35111, 3.63155, 7.229498], [18.15111, 3.631447, 5.383497], [16.35111, 3.63155, 5.383497]]
  perturbation_bound: [2.0, 2.0, 5.0]
Gate11:
  nominal_location: [[-27.01367, 2.543159, 7.515942], [-28.81367, 2.543289, 7.515942], [-27.01367, 2.543159, 5.669941], [-28.81367, 2.543289, 5.669941]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate12:
  nominal_location: [[18.40823, 13.60605, 9.143385], [16.33437, 14.09245, 9.143507], [18.90706, 15.73291, 9.14324], [16.83319, 16.21931, 9.143364]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate23:
  nominal_location: [[-9.328671, 7.773174, 2.942941], [-11.12867, 7.773277, 2.942941], [-9.328669, 7.773174, 1.096941], [-11.12867, 7.773277, 1.096941]]
  perturbation_bound: [5.0, 5.0 ,5.0]
Gate6:
  nominal_location: [[-9.14867, 30.62316, 3.820941], [-10.94867, 30.62329, 3.820941], [-9.148668, 30.62316, 1.974941], [-10.94867, 30.62329, 1.974941]]
  perturbation_bound: [0.0, 0.0, 2.0]
Gate2:
  nominal_location: [[0.8248205, 27.86797, 4.16025], [3.834821, 27.86797, 4.16025], [3.834821, 27.86797, 0.9327497], [0.8248205, 27.86797, 0.9327497]]
  perturbation_bound: [0.0, 1.0, 5.0]
Gate14:
  nominal_location: [[-8.674376, -29.53623, 4.25625], [-6.545984, -27.40784, 4.25625], [-6.545984, -27.40784, 1.02875], [-8.674376, -29.53623, 1.02875]]
  perturbation_bound: [1.0, 1.0, 5.0]
Gate15:
  nominal_location: [[5.744822, -11.79203, 4.16025], [8.75482, -11.79203, 4.16025], [8.75482, -11.79203, 0.9327497], [5.744822, -11.79203, 0.9327497]]
  perturbation_bound: [0.0, 2.5, 5.0]
Gate16:
  nominal_location: [[-13.73218, 28.64197, 12.65825], [-13.73218, 26.23396, 12.65825], [-13.73218, 26.23396, 10.07625], [-13.73218, 28.64197, 10.07625]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate17:
  nominal_location: [[-20.57, -13.29803, 3.46425], [-20.57, -15.70603, 3.46425], [-20.57, -15.70603, 0.8822498], [-20.57, -13.29803, 0.8822498]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate18:
  nominal_location: [[13.51782, 21.76397, 3.61825], [13.51782, 19.35596, 3.61825], [13.51782, 19.35596, 1.03625], [13.51782, 21.76397, 1.03625]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate19:
  nominal_location: [[15.96136, -17.26184, 12.31488], [18.36892, -17.26184, 12.36067], [18.41802, -17.26184, 9.779139], [16.01046, -17.26184, 9.733349]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate20:
  nominal_location: [[-25.39118, 25.019, 7.856133], [-22.98318, 25.019, 7.856133], [-22.98318, 25.019, 5.274133], [-25.39118, 25.019, 5.274133]]
  perturbation_bound: [0.0, 0.0, 0.0]
Gate21:
  nominal_location: [[15.68563, 38.50578, 8.376249], [17.81402, 40.63416, 8.376249], [17.81402, 40.63416, 5.14875], [15.68563, 38.50578, 5.14875]]
  perturbation_bound: [0.0, 0.0, 2.0]
Gate22:
  nominal_location: [[4.803625, -27.37584, 4.18125], [6.932016, -29.50423, 4.18125], [6.932016, -29.50423, 0.9537499], [4.803625, -27.37584, 0.9537499]]
  perturbation_bound: [1.0, 1.0, 5.0]

