
# All sensors for new scenes & trjectories
#camera_list: [left_gray, right_gray, down_gray, left_rgb_blurred, down_rgb_blurred, left_depth, down_depth, left_segmented, down_segmented]


#camera_list: [left_rgb_blurred, down_rgb_blurred, left_segmented, down_segmented, left_depth, down_depth]
#camera_list: [left_rgb_blurred, down_rgb_blurred, left_segmented, down_segmented]
camera_list: [left_rgb_blurred]

# HEVC compressed IJRR sensors
#camera_list: [left_rgb_blurred, down_rgb_blurred, left_depth, down_depth, left_segmented, down_segmented]

# Raycasted depth sensors
#camera_list: [left_depth, down_depth]

# New environment grayscales.
#camera_list: [left_gray, right_gray, down_gray]


# enum outputShaderType {
#   RGB = -1,
#   InstanceID = 0,
#   SemanticID = 1,
#   DepthCompressed = 2,
#   DepthMultiChannel = 3,
#   SurfaceNormals =4
#   grayscale=5
# }


# Grayscale (120Hz)
left_gray:
    tf: left
    ID: "Camera_Left_Gray"
    motionBlurPercent: 0.0                     
    outputShaderType: 5
    hasCollisionCheck: true        

right_gray:
    tf: right
    ID: "Camera_Right_Gray"
    motionBlurPercent: 0.0                     
    outputShaderType: 5        
    hasCollisionCheck: true        

down_gray:
    tf: down
    ID: "Camera_Down_Gray"
    motionBlurPercent: 0.0                     
    outputShaderType: 5     
    hasCollisionCheck: true        

# Depth (120Hz/2 = 60Hz)
left_depth:
    tf: left
    ID: "Camera_Left_Depth"                     
    outputShaderType: 3        
    hasCollisionCheck: true        

down_depth:
    tf: down
    ID: "Camera_Down_Depth"
    outputShaderType: 3 
    hasCollisionCheck: true        

# RGB Blurred (120Hz/2 = 60Hz)
left_rgb_blurred:
    tf: left
    ID: "Camera_Left_RGB"
    motionBlurPercent: 0.0                     
    outputShaderType: -1       
    hasCollisionCheck: true        

# RGB Blurred (120Hz/2 = 60Hz)
right_rgb_blurred:
    tf: right
    ID: "Camera_RIGHT_RGB"
    motionBlurPercent: 1.0                     
    outputShaderType: -1       
    hasCollisionCheck: true        

down_rgb_blurred:
    tf: down
    ID: "Camera_Down_RGB"
    motionBlurPercent: 1.0                     
    outputShaderType: -1      
    hasCollisionCheck: true        

# Segmentation (120Hz/2 = 60Hz)
left_segmented:
    tf: left
    ID: "Camera_Left_Segmented"
    motionBlurPercent: 0.0                     
    outputShaderType: 1    
    hasCollisionCheck: true        

down_segmented:
    tf: down
    ID: "Camera_Down_Segmented"
    motionBlurPercent: 0.0                     
    outputShaderType: 1   
    hasCollisionCheck: true        


left_optic_flow:
    tf: left
    ID: "Camera_Left_OpticalFlow"
    motionBlurPercent: 0.0                     
    outputShaderType: 6    
    hasCollisionCheck: true        
 
